## PANDAS

#### Importons pandas

In [96]:
import pandas as pd

- Chargement d'un fichier csv

In [97]:
df = pd.read_csv('../data/performance-economique-du-secteur-reel-de-2010-a-2023.csv', sep=',', encoding='UTF8')
print(df)  # Vérifiez les noms des colonnes

                                    Indicateurs  Années  \
0                      Croissance du PIB réel %    2023   
1                      Croissance du PIB réel %    2022   
2                      Croissance du PIB réel %    2021   
3                      Croissance du PIB réel %    2020   
4                      Croissance du PIB réel %    2019   
5                      Croissance du PIB réel %    2018   
6                      Croissance du PIB réel %    2017   
7                      Croissance du PIB réel %    2016   
8                      Croissance du PIB réel %    2015   
9                      Croissance du PIB réel %    2014   
10                     Croissance du PIB réel %    2013   
11                     Croissance du PIB réel %    2012   
12                     Croissance du PIB réel %    2011   
13                     Croissance du PIB réel %    2010   
14              Taux d'investissements % du PIB    2023   
15              Taux d'investissements % du PIB    2022 

## Examinons maintenant nos données

 Nous utiliserons ici la fonction head() et tail()
- head(): Affiche les premières lignes
- tail(): Affiche les dernières lignes
### Par défaut ces fonctions affichent 5 lignes

In [98]:
# Affichons les 5 premières lignes
df.head()
# Affichons les 4 premières lignes
df.head(4)

Indicateurs  Années  fluctuations en pourcentage
0  Croissance du PIB réel %    2023                          7.2
1  Croissance du PIB réel %    2022                          6.9
2  Croissance du PIB réel %    2021                          7.4
3  Croissance du PIB réel %    2020                          2.0

In [99]:
# Affichons les 5 dernières lignes
df.tail()
# Affichons les 3 dernières lignes
df.tail(3)

Indicateurs  Années  \
40  Prix à la Consommation (Taux d'inflation) %    2012   
41  Prix à la Consommation (Taux d'inflation) %    2011   
42  Prix à la Consommation (Taux d'inflation) %    2010   

    fluctuations en pourcentage  
40                          1.3  
41                          4.9  
42                          1.2

- Pour connaître les dimensions d'un DataFrame, c'est à dire le nombre de colonne et de ligne qu'il contient, nous pouvons utiliser l'attribut shape de pandas

In [100]:
# Affichons le nombre de lignes et de colonnes
df.shape

(43, 3)

- Pour connaître les types de colonnes, variables d'un DataFrame, nous pouvons utiliser l'attribut de type() de pandas

In [101]:
# Les types de lignes et de colonnes
df.dtypes

Indicateurs                     object
Années                           int64
fluctuations en pourcentage    float64
dtype: object

- Le problème vient des guillemets autour du nom de la colonne "Années". Dans votre DataFrame, le nom de la colonne est littéralement "Années" (avec les guillemets inclus), ce qui explique pourquoi df['Années'] provoque une erreur.

In [102]:
df.columns = df.columns.str.replace('"', '')  # Supprime les guillemets des noms de colonnes
print(df.columns)  # Vérifiez les noms des colonnes après nettoyage

Index(['Indicateurs', 'Années', 'fluctuations en pourcentage'], dtype='object')


- Afficher le nom des colonnes de notre DataFrame colomns

- Comment accéder à l'une des colonnes de notre DataFrame

In [103]:
print(df['Années'])

0     2023
1     2022
2     2021
3     2020
4     2019
5     2018
6     2017
7     2016
8     2015
9     2014
10    2013
11    2012
12    2011
13    2010
14    2023
15    2022
16    2021
17    2020
18    2019
19    2018
20    2017
21    2016
22    2015
23    2014
24    2013
25    2012
26    2011
27    2010
28    2024
29    2023
30    2022
31    2021
32    2020
33    2019
34    2018
35    2017
36    2016
37    2015
38    2014
39    2013
40    2012
41    2011
42    2010
Name: Années, dtype: int64


- Essayons d'accéder à plusieur colonnes
- Il suffit de socker l'enssemble des noms de colonnes auxquelles ont souhaiterais accéder dans une liste
- Voilà par exemple comment selectionner la colonne Années et Indicateur de notre DataFrame

In [104]:
list = ['Années', 'Indicateurs'] # Liste des colonnes à sélectionner
df[list]  # Sélection des colonnes Années et Indicateur

Années                                  Indicateurs
0     2023                     Croissance du PIB réel %
1     2022                     Croissance du PIB réel %
2     2021                     Croissance du PIB réel %
3     2020                     Croissance du PIB réel %
4     2019                     Croissance du PIB réel %
5     2018                     Croissance du PIB réel %
6     2017                     Croissance du PIB réel %
7     2016                     Croissance du PIB réel %
8     2015                     Croissance du PIB réel %
9     2014                     Croissance du PIB réel %
10    2013                     Croissance du PIB réel %
11    2012                     Croissance du PIB réel %
12    2011                     Croissance du PIB réel %
13    2010                     Croissance du PIB réel %
14    2023              Taux d'investissements % du PIB
15    2022              Taux d'investissements % du PIB
16    2021              Taux d'investissements % du PIB
17    2020              Taux d'investissements % du PIB
18    2019              Taux d'investissements % du PIB
19    2018              Taux d'investissements % du PIB
20    2017              Taux d'investissements % du PIB
21    2016              Taux d'investissements % du PIB
22    2015              Taux d'investissements % du PIB
23    2014              Taux d'investissements % du PIB
24    2013              Taux d'investissements % du PIB
25    2012              Taux d'investissements % du PIB
26    2011              Taux d'investissements % du PIB
27    2010              Taux d'investissements % du PIB
28    2024  Prix à la Consommation (Taux d'inflation) %
29    2023  Prix à la Consommation (Taux d'inflation) %
30    2022  Prix à la Consommation (Taux d'inflation) %
31    2021  Prix à la Consommation (Taux d'inflation) %
32    2020  Prix à la Consommation (Taux d'inflation) %
33    2019  Prix à la Consommation (Taux d'inflation) %
34    2018  Prix à la Consommation (Taux d'inflation) %
35    2017  Prix à la Consommation (Taux d'inflation) %
36    2016  Prix à la Consommation (Taux d'inflation) %
37    2015  Prix à la Consommation (Taux d'inflation) %
38    2014  Prix à la Consommation (Taux d'inflation) %
39    2013  Prix à la Consommation (Taux d'inflation) %
40    2012  Prix à la Consommation (Taux d'inflation) %
41    2011  Prix à la Consommation (Taux d'inflation) %
42    2010  Prix à la Consommation (Taux d'inflation) %

- Modifier une colonne existante

In [94]:
# Modifier une colonne existante
df['Années'] = 0 # Remplace toutes les valeurs de la colonne Années par 0
df['Années'] # Vérifiez les modifications

0     0
32    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
33    0
22    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
23    0
21    0
1     0
10    0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
11    0
20    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
42    0
Name: Années, dtype: int64

- Modifions ensuite les valeurs de "Fluctuation en poucentage" et le multipliant par 2 

In [105]:
# Modifions ensuite les valeurs de "Fluction en poucentage" et le multipliant par 2
df['fluctuations en pourcentage'] = df['fluctuations en pourcentage'] * 2
df['fluctuations en pourcentage']  # Vérifiez les modifications

0     14.4
1     13.8
2     14.8
3      4.0
4     12.4
5     13.8
6     14.8
7     14.4
8     17.6
9     17.6
10    18.6
11    20.2
12    -8.4
13     4.0
14    54.8
15    47.4
16    46.8
17    44.8
18    42.2
19    39.6
20    40.2
21    43.0
22    47.4
23    37.8
24    34.0
25    25.4
26    18.0
27    24.6
28     7.0
29     8.8
30    10.4
31     8.4
32     4.8
33     1.6
34     0.8
35     1.4
36     1.4
37     2.6
38     0.8
39     5.2
40     2.6
41     9.8
42     2.4
Name: fluctuations en pourcentage, dtype: float64

- Création de colonne(Suivre la même technique que le code pour la modification)
Il suffit d'appeler la colonne comme si elle existait déjà et de lui attribué une valeur

In [106]:
# Creation de colonne
df['Agent économique'] = 'ange'  # Crée une nouvelle colonne avec la valeur 'Inconnu' pour toutes les lignes
df['Agent économique']  # Vérifiez la nouvelle colonne

0     ange
1     ange
2     ange
3     ange
4     ange
5     ange
6     ange
7     ange
8     ange
9     ange
10    ange
11    ange
12    ange
13    ange
14    ange
15    ange
16    ange
17    ange
18    ange
19    ange
20    ange
21    ange
22    ange
23    ange
24    ange
25    ange
26    ange
27    ange
28    ange
29    ange
30    ange
31    ange
32    ange
33    ange
34    ange
35    ange
36    ange
37    ange
38    ange
39    ange
40    ange
41    ange
42    ange
Name: Agent économique, dtype: object

- Supprimer une colonne existante

In [107]:
# Supprimer une colonne existante
df = df.drop(columns=['Agent économique'])  # Supprime la colonne 'Agent économique'
df.columns  # Vérifiez que la colonne a été supprimée

Index(['Indicateurs', 'Années', 'fluctuations en pourcentage'], dtype='object')

- Renommer une colonne

In [108]:
# Renommer une colonne
df = df.rename(columns={'fluctuations en pourcentage': 'Fluctuations (%)'})  # Renomme la colonne
df.columns  # Vérifiez le nouveau nom de la colonne

Index(['Indicateurs', 'Années', 'Fluctuations (%)'], dtype='object')

- Changer le type d'une colonne

In [109]:
# Changer le type d'une colonne
df['Années'] = df['Années'].astype(str)  # Change le type de la colonne 'Années' en chaîne de caractères
df.dtypes  # Vérifiez les types de données des colonnes

Indicateurs          object
Années               object
Fluctuations (%)    float64
dtype: object

- Trier les données

In [110]:
#Trier l'année par ordre ddécroissant
df = df.sort_values(by='Années', ascending=False)  # Trie les données par la colonne 'Années' en ordre décroissant
df.head()  # Vérifiez les premières lignes pour voir le tri

Indicateurs Années  Fluctuations (%)
28  Prix à la Consommation (Taux d'inflation) %   2024               7.0
0                      Croissance du PIB réel %   2023              14.4
14              Taux d'investissements % du PIB   2023              54.8
29  Prix à la Consommation (Taux d'inflation) %   2023               8.8
30  Prix à la Consommation (Taux d'inflation) %   2022              10.4

# NUMPY
- Numpy est une librairie Python essentielle pour les calculs numériques, permettant de manipuler efficacement des tableaux multidimensionnels. Contrairement aux listes, Numpy offre rapidité, homogénéité des types et compatibilité avec d'autres librairies. Ce cours présente les bases de Numpy, incluant la création et la manipulation de tableaux.

Voici les fonctionnalités principales de NumPy, extraites du document :

1. **Manipulation de tableaux multidimensionnels** :
   - NumPy permet de créer et de manipuler des tableaux multidimensionnels (vecteurs, matrices, etc.) de manière efficace.
   - Les tableaux NumPy sont homogènes, ce qui signifie que tous les éléments doivent être du même type de données.

2. **Performances optimisées** :
   - Contrairement aux listes Python, les tableaux NumPy sont beaucoup plus rapides pour les opérations sur de grandes quantités de données.
   - NumPy utilise une approche optimisée pour le calcul numérique.

3. **Syntaxe concise et intuitive** :
   - NumPy offre une syntaxe simplifiée pour effectuer des opérations sur les tableaux, comme les additions, multiplications, etc.

4. **Compatibilité avec d'autres librairies** :
   - NumPy est compatible avec d'autres librairies populaires comme Pandas et Scikit-learn, ce qui facilite son intégration dans des projets de science des données et d'apprentissage automatique.

5. **Fonctions intégrées pour la création de tableaux** :
   - `np.array()` : Convertit une liste ou un autre objet en tableau NumPy.
   - `np.zeros()` : Crée un tableau rempli de zéros.
   - `np.ones()` : Crée un tableau rempli de uns.
   - `np.linspace()` : Génère un tableau avec des nombres espacés uniformément.
   - `np.arange()` : Crée un tableau avec des valeurs dans une plage spécifiée et un pas donné.

6. **Redimensionnement et transformation** :
   - La fonction `reshape()` permet de modifier la forme d'un tableau (par exemple, convertir un vecteur en matrice).
   - La fonction `transpose()` (ou `T`) permet de permuter les lignes et les colonnes d'un tableau.

7. **Opérations mathématiques avancées** :
   - NumPy prend en charge des opérations mathématiques complexes comme les produits matriciels, les transformations trigonométriques, etc.

Ces fonctionnalités font de NumPy un outil indispensable pour les calculs scientifiques et l'analyse de données en Python.

### Import de la librairie

In [111]:
import numpy as np

### Creer un tableau avec numpy

In [ ]:
# Tableau numpy à une dimension
a = np.array([0,7,1,3,3,1,7,9]) # Creer un tableau avec numpy
print(a)

[0 7 1 3 3 1 7 9]


In [113]:
#Tableau numpy à deux dimensions
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Creer un tableau avec numpy
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [114]:
#Tableau numpy à trois dimensions
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]) # Creer un tableau avec numpy
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


### Création d'un DataFrame pour le budget des ministères

In [ ]:
data = {
    'Ministères:': ['Education', 'Santé', 'Défense', 'Finances'],
    'Budget_Alloue': [5000, 3000, 4000, 6000],
    'Budget_Utilise': [4500, 2800, 3900, 5800],
    'Année': [2025, 2025, 2025, 2025],
}

df_Budget = pd.DataFrame(data)
print(df_Budget)

  Ministères:  Budget_Alloue  Budget_Utilise  Année
0   Education           5000            4500   2022
1       Santé           3000            2800   2022
2     Défense           4000            3900   2022
3    Finances           6000            5800   2022


In [ ]:
# Création du DataFrame
data_regions = {
    'Région': ['Abidjan', 'Yamoussoukro', 'San-Pédro', 'Bouaké', 'Korhogo'],
    'Recettes_Fiscales': [120.5, 45.3, 38.7, 52.1, 40.8],
    'Dépenses_Publiques': [115.2, 48.1, 42.3, 50.5, 43.2],
    'Investissements': [25.3, 12.5, 8.7, 15.2, 10.4],
    'Déficit': [None, 2.8, 3.6, -1.6, 2.4]
}

df_regions = pd.DataFrame(data_regions)

# 1. Informations de base
print("1. INFORMATIONS DE BASE:")
print(df_regions.info())
print("\nAperçu des données:")
print(df_regions.head())

# 2. Calcul du solde budgétaire
df_regions['Solde_Budgétaire'] = df_regions['Recettes_Fiscales'] - df_regions['Dépenses_Publiques']
print("\n2. SOLDE BUDGÉTAIRE PAR RÉGION:")
print(df_regions[['Région', 'Solde_Budgétaire']])

# 3. Traitement des données manquantes
print("\n3. DONNÉES MANQUANTES AVANT TRAITEMENT:")
print(df_regions.isnull().sum())

# Remplissage des valeurs manquantes par la moyenne
deficit_moyen = df_regions['Déficit'].mean()
df_regions['Déficit'].fillna(deficit_moyen, inplace=True)
print("\nAprès traitement des données manquantes:")
print(df_regions)

# 4. Région avec les recettes les plus élevées
region_max_recettes = df_regions.loc[df_regions['Recettes_Fiscales'].idxmax(), 'Région']
print(f"\n4. RÉGION AVEC RECETTES MAXIMALES: {region_max_recettes}")

# 5. Moyenne des investissements
moyenne_investissements = df_regions['Investissements'].mean()
print(f"\n5. MOYENNE DES INVESTISSEMENTS: {moyenne_investissements:.2f} milliards FCFA")

# 6. Régions avec déficit > 2 milliards
regions_deficit_eleve = df_regions[df_regions['Déficit'] > 2]
print("\n6. RÉGIONS AVEC DÉFICIT > 2 MILLIARDS:")
print(regions_deficit_eleve[['Région', 'Déficit']])

1. INFORMATIONS DE BASE:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Région              5 non-null      object 
 1   Recettes_Fiscales   5 non-null      float64
 2   Dépenses_Publiques  5 non-null      float64
 3   Investissements     5 non-null      float64
 4   Déficit             4 non-null      float64
dtypes: float64(4), object(1)
memory usage: 332.0+ bytes
None

Aperçu des données:
         Région  Recettes_Fiscales  Dépenses_Publiques  Investissements  \
0       Abidjan              120.5               115.2             25.3   
1  Yamoussoukro               45.3                48.1             12.5   
2     San-Pédro               38.7                42.3              8.7   
3        Bouaké               52.1                50.5             15.2   
4       Korhogo               40.8                43.2             10.4   

C:\Users\ange\AppData\Local\Temp\ipykernel_9440\1995230513.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_regions['Déficit'].fillna(deficit_moyen, inplace=True)
